"""add_transcribe_histories_table_and_relation

Revision ID: 0a25a7b941b3
Revises: 186994790ca0
Create Date: 2025-05-04 12:03:57.457308

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a25a7b941b3"
down_revision: Union[str, None] = "186994790ca0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transcribe_histories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("episode_id", sa.String(), nullable=False),
        sa.Column("model_name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "episode_segments",
        sa.Column("transcribe_history_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "episode_segments",
        "transcribe_histories",
        ["transcribe_history_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "episode_segments", type_="foreignkey")
    op.drop_column("episode_segments", "transcribe_history_id")
    op.drop_table("transcribe_histories")
    # ### end Alembic commands ###
