"""add ext column to episodes table

Revision ID: 186994790ca0
Revises: ebc1816be7ce
Create Date: 2025-05-03 09:23:10.728422

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "186994790ca0"
down_revision: Union[str, None] = "ebc1816be7ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("episodes", sa.Column("ext", sa.String(), nullable=True))
    # ### end Alembic commands ###

    # Populate ext column for existing records based on media_type
    conn = op.get_bind()

    # Update records with media_type = 'audio/mpeg' to ext = 'mp3'
    conn.execute(
        text("UPDATE episodes SET ext = 'mp3' WHERE media_type = 'audio/mpeg'")
    )

    # Update records with media_type = 'audio/wav' to ext = 'wav'
    conn.execute(text("UPDATE episodes SET ext = 'wav' WHERE media_type = 'audio/wav'"))

    # Update records with media_type in ('audio/x-m4a', 'audio/mp4') to ext = 'm4a'
    conn.execute(
        text(
            "UPDATE episodes SET ext = 'm4a' WHERE media_type IN ('audio/x-m4a', 'audio/mp4')"
        )
    )

    # Set default 'mp3' for any remaining records with NULL ext
    conn.execute(text("UPDATE episodes SET ext = 'mp3' WHERE ext IS NULL"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("episodes", "ext")
    # ### end Alembic commands ###
