"""add hash column to episodes table

Revision ID: ebc1816be7ce
Revises: 
Create Date: 2025-05-02 15:41:54.063101

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ebc1816be7ce"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("episodes", sa.Column("hash", sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, "episodes", ["hash"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "episodes", type_="unique")
    op.drop_column("episodes", "hash")
    # ### end Alembic commands ###
